version: "3.5"

services:
  docker-dashboard-ui:
    image: docker-dashboard-ui-configurable
    environment:
      DASHBOARD_HOST: ${DASHBOARD_HOST}
      DASHBOARD_PORT: ${DASHBOARD_PORT}
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: DockerDashboardUI.Client/Dockerfile
