version: '3.5'

services:
  docker-dashboard-ui:
    image: docker-dashboard-ui
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: DockerDashboardUI.Client/Dockerfile
    